# Generated by Django 6.0 on 2025-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/Posts/'),
        ),
    ]
