# Generated by Django 6.0 on 2026-01-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_likes_post_alter_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True),
        ),
    ]
